### Find all schedules
GET http://localhost:8080/schedules

### Find schedule with id

GET http://localhost:8080/schedules/3

### Create a new schedule
POST http://localhost:8080/schedules
Content-Type: application/json

{
    "service": "Haircut",
    "professional": "John Doe",
    "scheduledDateTime": "2024-07-01T10:00:00",
    "client": "Jane Smith",
    "contact": "555-1234"
}

### Get schedules by date
GET http://localhost:8080/schedules/date/2026-02-15

### Update schedule
PATCH http://localhost:8080/schedules
Content-Type: application/json

{
    "oldDate": "2026-02-15T09:00:00",
    "newDate": "2026-02-25T09:00:00",
    "client": "André Luiz Pereira"
}